# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    # -   id: check-added-large-files   # (For now only) venv files exceeds the maximum size

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v1.9.0'
#     hooks:
#       - id: mypy
#         additional_dependencies: [ types-requests, types-PyYAML, types-toml ]
#         exclude: venv/lib/python3.10/site-packages/typing_extensions.py
